### ISSUE TITLE
pytorch DDP

### ISSUE THREAD

**Issue by childult-programmer** [imatif17/ACIA#1]
Thanks for the good research.

During the training on DDP, the previous code ‘Prototype Mean Teacher’ was not becoming DDP from Stage-2, (Ref:  https://github.com/imatif17/Prototype-Mean-Teacher/issues/5)
What is the difference in this code that makes DDP mode possible?

**Comment by childult-programmer** [comment]
Sorry, Ref: https://github.com/imatif17/Prototype-Mean-Teacher/issues/5

**Comment by imatif17** [comment]
Please, read the comment on the line 399 of acia/engine/trainer.py

**Comment by imatif17** [comment]
We're calculating instance-level alignment even in the burn-in step. Then, weighing it down to zero. Just to get gradient for instance-alignment parameters as DDP expects gradient for every parameters in the model.
